---
- name: Upgrade Arch Linux
  hosts: all
  become: yes
  tasks:
    - name: Remount root filesystem as read-write
      command: mount -o remount,rw /
      when: ansible_os_family == 'Archlinux'

    - name: Upgrade Arch Linux
      command: pacman -Syu --noconfirm
      when: ansible_os_family == 'Archlinux'

    - name: Remount root filesystem as read-only
      command: mount -o remount,ro /
      when: ansible_os_family == 'Archlinux'
